### ISSUE TITLE
特殊文字のエスケープ

### ISSUE THREAD

**Issue by 2ndr9** [tomoki52/scrap-paper-bookmarklet#3]
学会名が「Interacción」の場合，Scarpbox上では「Interacci&#xf3;n」になる

**Comment by tomoki52** [comment]
何が違うのか分からなかったです．「Interaccion」になってほしいということ？

**Comment by 2ndr9** [comment]
あ，デコードされてしまった

`Interacción`となってほしいが，
`Interacci&#xf3;n`になるということです

**Comment by tomoki52** [comment]
~ちょっと調べたんだけど解決方法が分からなかった  
Interacciónだけなら`replace("&#xf3;", "ó");`としてもいいんだけど流石にもっといい方法がある気がする~

https://nodoame.net/archives/7014 これかも？

**Comment by 2ndr9** [comment]
`document.getElementsByClassName("epub-section__title")[0].innerText`
でいけそう

というのは
<img width="713" alt="image" src="https://user-images.githubusercontent.com/53454871/209896156-c97a55a6-e101-47d2-838f-ac7d801c92c8.png">
のように，span内のinnerTextならエンコードされてないから
